export const products = [
	{
		id: 1,
		title: "Jordan Air 1 Low",
		precio: 57000,
		stock: 3,
		description: "Zapatillas Urbanas Nike Blancas y Azul",
		category: "mujer",
		img: "https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw76f76351/products/NIDC0774-141/NIDC0774-141-1.JPG",
	},
	{
		id: 2,
		title: "Puma Slipstream Tr",
		precio: 43000,
		stock: 5,
		description: "Zapatillas Urbanas Puma Negras",
		category: "unisex",
		img: "https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dwe305cdf5/products/PU388992-04/PU388992-04-1.JPG",
	},
	{
		id: 3,
		title: "Puma Rs-fast Limiter Neon Unisex",
		precio: 43000,
		stock: 4,
		description: "Zapatillas Deportivas Puma Negras",
		category: "unisex",
		img: "https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dwfb0c225f/products/PU388102-01/PU388102-01-1.JPG",
	},
	{
		id: 4,
		title: "Nike Waffle One Ess",
		precio: 50000,
		stock: 2,
		description: "Zapatillas Deportivas Nike Rosadas",
		category: "mujer",
		img: "https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw84c6f975/products/NI_DM7604-600/NI_DM7604-600-1.JPG",
	},
	{
		id: 5,
		title: "Nike Dunk Low SE",
		precio: 57000,
		stock: 6,
		description: "Zapatillas Urbanas Nike Naranjas",
		category: "hombre",
		img: "https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw2faa8c09/products/NIDZ5350-288/NIDZ5350-288-1.JPG",
	},
	{
		id: 6,
		title: "Adidas Nmd R1 V3",
		precio: 54000,
		stock: 5,
		description: "Zapatillas Deportivas Adidas Gris",
		category: "unisex",
		img: "https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw14e746c9/products/ADGY4146/ADGY4146-1.JPG",
	},
	{
		id: 7,
		title: "Vans Ultra Range Rapidweld",
		precio: 47000,
		stock: 4,
		description: "Zapatillas Deportivas Vans Gris",
		category: "unisex",
		img: "https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw0b785a53/products/VA_VN0A5HYSBAT/VA_VN0A5HYSBAT-1.JPG",
	},
	{
		id: 8,
		title: "Vans Old Skool",
		precio: 50000,
		stock: 7,
		description: "Zapatillas Deportivas Vans Negras",
		category: "hombre",
		img: "https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dweebb8875/products/VA_VN000D3HBKA/VA_VN000D3HBKA-1.JPG",
	},
];
